[tool.poetry]
name = "tadqeek_sakhr"
version = "0.1.0"
description = "A mini command line tool to spellcheck text files using tadqeek.alsharekh.org"
authors = ["yshalsager <ysh-alsager@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
