name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application for Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: tadqeek_sakhr.exe
        path: dist/windows
        
    - name: Package Application for Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: tadqeek_sakhr
        path: dist/linux

    - name: Get Short SHA
      id: sha_short
      run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.sha_short.outputs.sha_short }}
        name: ${{ steps.sha_short.outputs.sha_short }}
        files: |
          dist/windows/tadqeek_sakhr.exe
          dist/linux/tadqeek_sakhr

