name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application for Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: tadqeek_alsharekh_org.exe
        path: dist/windows
        
    - name: Package Application for Linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: tadqeek_alsharekh_org
        path: dist/linux

    - name: Get Short SHA
      id: sha_short
      run: echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.sha_short.outputs.sha_short }}
        allow_override: true
        files: >
          dist/windows/tadqeek_alsharekh_org.exe
          dist/linux/tadqeek_alsharekh_org

